### ISSUE TITLE
Reconfigure "Send Files"/"Next Page" buttons on Record page

### ISSUE THREAD

**Issue by sdnorris** [joelyjoel/singing-our-lives#40]
There are two folders in formfills that contain a "feedback.json," but no accompanying media.  I'm guessing that this may have been because people forgot to click "Send Files" before continuing past the Record page.
This could be addressed by either:

- removing the "Send Files" button and attaching its functionality to the "Continue" button (i.e. clicking continue would send the files and then navigate to the next page
-hiding the continue button until after the "Send Files" button has been clicked (risk with this is that it prevents people from getting to the text feedback on the Thank You page without uploading files, which they might want to do)

**Comment by joelyjoel** [comment]
I think the quickest solution is to create an event emitter on the `MediaUploads` class for which fires when after the files have been sent (or after they have started sending) to the server. In the html file you can then add a listener to this which turns to the next page.
